TICKET_CATALOG = [
    {
        "id": "user_locked_login",
        "title": "User cannot log in because the SAP user is locked",
        "area": "Security",
        "symptoms": ["user cannot login", "user locked", "login failed", "password locked"],
        "keywords": ["login", "locked", "user", "password", "unlock"],
        "error_signals": ["user locked", "logon not possible", "password expired"],
        "tcodes": ["SU01", "SUIM"],
        "root_cause": "The user master record is locked or the password is invalid or expired.",
        "checks": [
            "Review the user status and lock flags in SU01.",
            "Check whether the password is expired or multiple bad logons triggered the lock.",
            "Confirm the client, user type, and validity dates.",
        ],
        "resolution": [
            "Unlock the user in SU01.",
            "Reset the password if needed and share the temporary password securely.",
            "Verify user validity dates and assigned roles before retesting.",
        ],
        "escalate_if": [
            "The lock keeps returning after unlock.",
            "Several users are locked at the same time.",
        ],
    },
    {
        "id": "authorization_missing",
        "title": "Authorization error for dialog transaction or report",
        "area": "Security",
        "symptoms": ["authorization error", "not authorized", "missing authorization"],
        "keywords": ["authorization", "role", "access", "su53", "pfcg"],
        "error_signals": ["not authorized", "no authorization", "authorization check failed"],
        "tcodes": ["SU53", "PFCG", "SUIM", "ST01"],
        "root_cause": "A required authorization object or role assignment is missing.",
        "checks": [
            "Capture the failed action and immediately run SU53 for the affected user.",
            "Check the assigned role and authorization objects in PFCG.",
            "If the issue is unclear, trace the authorization check with ST01.",
        ],
        "resolution": [
            "Add the missing authorization in the correct role.",
            "Regenerate the role profile and ensure it reaches the user buffer.",
            "Retest the exact failed transaction with the business user.",
        ],
        "escalate_if": [
            "The required access conflicts with SoD rules.",
            "The change needs security approval or firefighter access.",
        ],
    },
    {
        "id": "background_job_authorization",
        "title": "Background job cancelled because of missing authorization",
        "area": "Basis",
        "symptoms": ["background job cancelled", "job failed", "batch job authorization"],
        "keywords": ["background", "job", "cancelled", "authorization", "sm37"],
        "error_signals": ["authorization missing", "job cancelled", "cancelled after job start"],
        "tcodes": ["SM37", "SM36", "PFCG", "SU53"],
        "root_cause": "The batch user or scheduled job lacks the authorization needed at runtime.",
        "checks": [
            "Inspect the job log and spool in SM37.",
            "Identify the technical user or background user used by the job.",
            "Validate missing authorizations with SU53 or ST01.",
        ],
        "resolution": [
            "Assign the missing authorization to the batch role.",
            "Recreate or reschedule the job if the step definition is outdated.",
            "Rerun the job and confirm successful completion.",
        ],
        "escalate_if": [
            "The job owns critical month-end or integration processing.",
            "The role change needs approval from security governance.",
        ],
    },
    {
        "id": "transport_rc8",
        "title": "Transport import failed with RC 8",
        "area": "Basis",
        "symptoms": ["transport failed", "rc 8", "transport import error"],
        "keywords": ["transport", "rc", "stms", "import", "object"],
        "error_signals": ["rc 8", "return code 8", "object missing"],
        "tcodes": ["STMS", "SE09", "SE10", "SE03"],
        "root_cause": "The import encountered missing objects, inactive dependencies, or sequence issues.",
        "checks": [
            "Review the import log in STMS for the exact object and phase failure.",
            "Check whether prerequisite transports are missing or out of sequence.",
            "Validate object locks and repair status in SE03 or transport organizer.",
        ],
        "resolution": [
            "Import prerequisite transports first or rebuild the transport sequence.",
            "Re-release or recreate the request if objects are inconsistent.",
            "Re-import the transport in STMS and confirm clean activation.",
        ],
        "escalate_if": [
            "The failed transport affects production or business-critical releases.",
            "Repository inconsistencies require ABAP or Basis admin intervention.",
        ],
    },
    {
        "id": "short_dump_memory",
        "title": "Short dump TSV_TNEW_PAGE_ALLOC_FAILED or memory-related dump",
        "area": "Basis",
        "symptoms": ["short dump", "memory issue", "tsv_tnew_page_alloc_failed"],
        "keywords": ["dump", "memory", "tsv_tnew_page_alloc_failed", "st22", "rz10"],
        "error_signals": ["tsv_tnew_page_alloc_failed", "no more memory available"],
        "tcodes": ["ST22", "RZ10", "ST06", "SM50"],
        "root_cause": "A program or work process exceeded available memory limits or caused abnormal memory growth.",
        "checks": [
            "Open the dump in ST22 and identify the ABAP program and user.",
            "Check OS and instance memory usage in ST06.",
            "Inspect long-running work processes in SM50 or SM66.",
        ],
        "resolution": [
            "Tune memory parameters in RZ10 if the system is consistently undersized.",
            "Optimize or split the ABAP selection volume causing the dump.",
            "Retest after memory tuning or program adjustment.",
        ],
        "escalate_if": [
            "The dump is recurring in production.",
            "An ABAP code fix is required to reduce selection size or memory usage.",
        ],
    },
    {
        "id": "system_slow_high_cpu",
        "title": "System performance issue with high CPU or slow response",
        "area": "Basis",
        "symptoms": ["system running slow", "high cpu", "performance issue", "slow response"],
        "keywords": ["slow", "performance", "cpu", "st06", "st03n", "sm50"],
        "error_signals": ["high cpu usage", "system slow", "response time high"],
        "tcodes": ["ST06", "ST03N", "SM50", "SM66", "DBACOCKPIT"],
        "root_cause": "Host resource pressure, expensive SQL, blocked work processes, or runaway jobs are degrading response time.",
        "checks": [
            "Check host CPU, memory, and disk in ST06.",
            "Review workload and response times in ST03N.",
            "Inspect active work processes and long-running tasks in SM50 or SM66.",
        ],
        "resolution": [
            "Stop or reschedule runaway jobs during peak business hours.",
            "Investigate expensive SQL or locking hotspots with DB and ABAP teams.",
            "Optimize work process usage and confirm response times recover.",
        ],
        "escalate_if": [
            "The slowdown impacts multiple modules or all users.",
            "Database or infrastructure tuning is required.",
        ],
    },
    {
        "id": "rfc_connection_failed",
        "title": "RFC destination failed because of wrong credentials or connectivity",
        "area": "Integration",
        "symptoms": ["rfc connection failed", "sm59 error", "destination failed"],
        "keywords": ["rfc", "sm59", "destination", "credentials", "connection"],
        "error_signals": ["wrong credentials", "logon failure", "partner not reached"],
        "tcodes": ["SM59", "SMGW", "ST22"],
        "root_cause": "The RFC destination has invalid credentials, network issues, or target system communication problems.",
        "checks": [
            "Test the destination in SM59 for connection and authorization.",
            "Validate the maintained user, password, and client details.",
            "Check gateway and network reachability if the partner is not reached.",
        ],
        "resolution": [
            "Correct the credentials and technical settings in SM59.",
            "Coordinate network or gateway fixes if the host is unreachable.",
            "Retest both connection and remote logon after changes.",
        ],
        "escalate_if": [
            "The target system is down or a network/firewall change is needed.",
            "The RFC is used by critical interfaces or postings.",
        ],
    },
    {
        "id": "database_full",
        "title": "Database or tablespace full",
        "area": "Basis",
        "symptoms": ["database full", "tablespace full", "db full"],
        "keywords": ["database", "tablespace", "db02", "dbacockpit", "space"],
        "error_signals": ["tablespace full", "no space left", "database full"],
        "tcodes": ["DB02", "DBACOCKPIT", "ST04"],
        "root_cause": "Database growth exceeded available tablespace or filesystem capacity.",
        "checks": [
            "Review tablespace usage and growth in DB02 or DBACOCKPIT.",
            "Identify the objects or logs consuming unusual space.",
            "Check whether archiving, cleanup, or filesystem growth failed.",
        ],
        "resolution": [
            "Extend the affected tablespace or filesystem.",
            "Perform approved cleanup or archiving for obsolete data or logs.",
            "Confirm database growth stabilizes after remediation.",
        ],
        "escalate_if": [
            "Production is near outage because no space remains.",
            "DBA or infrastructure action is required immediately.",
        ],
    },
    {
        "id": "update_terminated",
        "title": "Update terminated because V1 update failed",
        "area": "Basis",
        "symptoms": ["update terminated", "v1 update failed", "sm13 issue"],
        "keywords": ["update", "sm13", "terminated", "v1", "posting"],
        "error_signals": ["v1 update failed", "update terminated"],
        "tcodes": ["SM13", "SM21", "ST22"],
        "root_cause": "A failed update record blocked final database posting due to data inconsistency or technical failure.",
        "checks": [
            "Inspect failed update records in SM13.",
            "Review dumps and system logs related to the failed LUW.",
            "Identify whether the root cause is data, authorization, lock, or code related.",
        ],
        "resolution": [
            "Fix the underlying error and reprocess the failed update in SM13.",
            "Validate document consistency before retrying the business transaction.",
            "Confirm the update queue is clean after reprocessing.",
        ],
        "escalate_if": [
            "Financial or logistics postings are left inconsistent.",
            "A code defect or master data correction is needed.",
        ],
    },
    {
        "id": "lock_entry_issue",
        "title": "Business transaction blocked by lock entry",
        "area": "Basis",
        "symptoms": ["object locked", "lock entry issue", "record locked"],
        "keywords": ["lock", "sm12", "object", "entry", "blocked"],
        "error_signals": ["object locked", "locked by user", "enqueue failure"],
        "tcodes": ["SM12", "SM21", "SM50"],
        "root_cause": "A stale or active enqueue lock is preventing the transaction from proceeding.",
        "checks": [
            "Check the lock owner, table, and timestamp in SM12.",
            "Confirm whether another user or process is legitimately working on the object.",
            "Review work processes if the lock appears stale.",
        ],
        "resolution": [
            "Remove stale locks carefully in SM12 after confirming business impact.",
            "Ask the active user to complete or exit the transaction if the lock is valid.",
            "Retest the transaction after the lock is cleared.",
        ],
        "escalate_if": [
            "The same lock reappears immediately.",
            "Mass locking affects many users or critical jobs.",
        ],
    },
    {
        "id": "invoice_reversal",
        "title": "Need to reverse a posted FI invoice",
        "area": "FI",
        "symptoms": ["reverse invoice", "invoice reversal", "posted invoice wrong"],
        "keywords": ["reverse", "invoice", "fb08", "fi", "document"],
        "error_signals": ["reverse invoice", "wrong invoice posted"],
        "tcodes": ["FB08", "FB03", "FBRA"],
        "root_cause": "A posted accounting document needs formal reversal to maintain document integrity.",
        "checks": [
            "Confirm the original document number and fiscal period in FB03.",
            "Check whether the document is cleared or already partially reversed.",
            "Verify reversal reason and posting period availability.",
        ],
        "resolution": [
            "Use FB08 for standard reversal with the correct reversal reason and date.",
            "If clearing is involved, review whether reset clearing is needed first.",
            "Validate the reversal document and downstream impact after posting.",
        ],
        "escalate_if": [
            "The posting period is closed.",
            "The document is tied to payment, asset, or tax processes needing FI approval.",
        ],
    },
    {
        "id": "posting_period_closed_fi",
        "title": "FI posting period is closed",
        "area": "FI",
        "symptoms": ["posting period not open", "period closed", "cannot post fi document"],
        "keywords": ["posting", "period", "closed", "ob52", "fi"],
        "error_signals": ["posting period not open", "period closed"],
        "tcodes": ["OB52", "FB50", "FB60"],
        "root_cause": "The fiscal posting period is not open for the company code and account type.",
        "checks": [
            "Review the company code and account type involved in the error.",
            "Check open intervals in OB52.",
            "Confirm whether the intended period should be opened per finance controls.",
        ],
        "resolution": [
            "Open the correct posting period in OB52 if approved.",
            "Retry the posting after verifying the period interval.",
            "Close the temporary opening again if a controlled exception was used.",
        ],
        "escalate_if": [
            "Finance approval is required to open the period.",
            "Month-end controls prohibit additional postings.",
        ],
    },
    {
        "id": "spool_output_issue",
        "title": "Spool request created but output is not printing",
        "area": "Basis",
        "symptoms": ["spool error", "print output missing", "spool request not printing"],
        "keywords": ["spool", "print", "output", "sp01", "spad"],
        "error_signals": ["spool request failed", "output request error"],
        "tcodes": ["SP01", "SPAD", "SM50"],
        "root_cause": "The spool or output device is misconfigured, unavailable, or blocked.",
        "checks": [
            "Review spool and output request status in SP01.",
            "Validate printer device settings and access method in SPAD.",
            "Check whether the spool work process is available.",
        ],
        "resolution": [
            "Correct the output device or host spool configuration in SPAD.",
            "Reprocess the spool request after the device is available.",
            "Confirm printing works with a fresh test output.",
        ],
        "escalate_if": [
            "Printer server or network queue is down.",
            "Multiple devices or all spool outputs are failing.",
        ],
    },
    {
        "id": "idoc_status_51",
        "title": "IDoc stuck in status 51",
        "area": "Integration",
        "symptoms": ["idoc failed", "status 51", "idoc error"],
        "keywords": ["idoc", "51", "we02", "bd87", "ale"],
        "error_signals": ["status 51", "application document not posted"],
        "tcodes": ["WE02", "WE05", "BD87", "SM58"],
        "root_cause": "The IDoc failed application posting due to master data, configuration, or transient interface issues.",
        "checks": [
            "Review the status record and error message in WE02 or WE05.",
            "Confirm whether the issue is master data, partner profile, or posting logic.",
            "Check for pending tRFC issues in SM58 if relevant.",
        ],
        "resolution": [
            "Fix the underlying master data or configuration error.",
            "Reprocess the failed IDoc in BD87.",
            "Confirm the target document posts successfully after correction.",
        ],
        "escalate_if": [
            "A large interface backlog is building.",
            "The failure is caused by ABAP mapping or external middleware.",
        ],
    },
    {
        "id": "qrfc_stuck",
        "title": "qRFC queue stuck or not processing",
        "area": "Integration",
        "symptoms": ["queue stuck", "qrfc issue", "smq1", "smq2"],
        "keywords": ["queue", "qrfc", "smq1", "smq2", "stuck"],
        "error_signals": ["sysfail", "stopped queue", "queue stuck"],
        "tcodes": ["SMQ1", "SMQ2", "SM58", "ST22"],
        "root_cause": "Queued RFC processing stopped because of application errors, SYSFAIL, or locking dependencies.",
        "checks": [
            "Inspect queue status and last error in SMQ1 or SMQ2.",
            "Review related dumps or tRFC errors.",
            "Check whether queue serialization or lock dependency is blocking processing.",
        ],
        "resolution": [
            "Fix the underlying application or authorization error.",
            "Restart or unlock the affected queue after the root cause is cleared.",
            "Monitor queue throughput until the backlog is drained.",
        ],
        "escalate_if": [
            "Replication or core integration is blocked.",
            "The queue repeatedly falls into SYSFAIL.",
        ],
    },
    {
        "id": "work_process_exhaustion",
        "title": "No dialog or background work process available",
        "area": "Basis",
        "symptoms": ["no work process", "all work processes busy", "work process issue"],
        "keywords": ["work", "process", "sm50", "sm66", "busy"],
        "error_signals": ["no batch work process available", "no dialog work process available"],
        "tcodes": ["SM50", "SM66", "RZ04", "ST03N"],
        "root_cause": "Work processes are exhausted by long-running jobs, locks, or workload imbalance.",
        "checks": [
            "Review active work processes in SM50 and global overview in SM66.",
            "Identify blocked or long-running processes and the owning user.",
            "Check operation mode and work process allocation in RZ04.",
        ],
        "resolution": [
            "Stop or reschedule problematic jobs when safe.",
            "Tune operation modes or increase appropriate work process counts.",
            "Validate that user response and queue times recover.",
        ],
        "escalate_if": [
            "Instance restart or profile changes are required.",
            "The issue recurs because of application logic or database waits.",
        ],
    },
    {
        "id": "batch_job_variant_missing",
        "title": "Background job failed because a variant or spool setup is missing",
        "area": "Basis",
        "symptoms": ["job cancelled", "variant missing", "job not scheduled properly"],
        "keywords": ["job", "variant", "sm37", "sm36", "spool"],
        "error_signals": ["variant does not exist", "spool parameters incorrect"],
        "tcodes": ["SM37", "SM36", "SE38", "SA38"],
        "root_cause": "The scheduled job references a missing variant, invalid selection, or bad spool configuration.",
        "checks": [
            "Inspect the job log in SM37.",
            "Validate the program variant and spool settings in the job definition.",
            "Check whether transports or client copies removed the referenced variant.",
        ],
        "resolution": [
            "Recreate or correct the variant and spool parameters.",
            "Reschedule the job with the updated configuration.",
            "Run a controlled test execution before handing it back to business users.",
        ],
        "escalate_if": [
            "The failed job is part of period-end or regulatory processing.",
            "The program logic needs an ABAP fix.",
        ],
    },
    {
        "id": "po_release_issue",
        "title": "Purchase order cannot be released because of workflow or authorization",
        "area": "MM",
        "symptoms": ["po release failed", "cannot release purchase order", "release strategy issue"],
        "keywords": ["po", "purchase", "release", "me28", "authorization"],
        "error_signals": ["release not possible", "no authorization to release"],
        "tcodes": ["ME28", "ME29N", "SU53", "PFCG"],
        "root_cause": "The release strategy conditions are not met or the releaser lacks authorization.",
        "checks": [
            "Verify the release status and strategy on the purchase order.",
            "Check the user authorization if release fails for a specific approver.",
            "Confirm document changes did not restart the release cycle unexpectedly.",
        ],
        "resolution": [
            "Correct release strategy configuration or document values if needed.",
            "Grant the required release authorization to the approver.",
            "Retest the release in ME28 or ME29N.",
        ],
        "escalate_if": [
            "Workflow customizing is broken across many documents.",
            "Approval matrix changes require MM functional approval.",
        ],
    },
    {
        "id": "migo_posting_period",
        "title": "Goods movement cannot post because MM period or stock conditions block it",
        "area": "MM",
        "symptoms": ["migo error", "goods movement failed", "period closed in mm"],
        "keywords": ["migo", "goods", "movement", "period", "stock"],
        "error_signals": ["posting only possible in periods", "deficit of stock"],
        "tcodes": ["MIGO", "MMPV", "MB5B", "MMBE"],
        "root_cause": "The MM period is not open or stock availability and valuation settings prevent posting.",
        "checks": [
            "Review the exact MIGO error text and movement type.",
            "Check MM period status in MMPV if the error is period related.",
            "Validate stock and valuation data in MMBE or stock reports.",
        ],
        "resolution": [
            "Open the correct MM period if approved.",
            "Correct stock, batch, or movement type data before reposting.",
            "Retry the movement and confirm the material document posts.",
        ],
        "escalate_if": [
            "Inventory balances are inconsistent.",
            "Material master or valuation customizing changes are required.",
        ],
    },
    {
        "id": "sales_pricing_condition_missing",
        "title": "Sales order pricing condition is missing",
        "area": "SD",
        "symptoms": ["pricing condition missing", "sales order price missing", "condition record not found"],
        "keywords": ["pricing", "condition", "sales", "order", "vk11", "va01"],
        "error_signals": ["condition record missing", "pricing error"],
        "tcodes": ["VA01", "VA02", "VK11", "VK13", "V/08"],
        "root_cause": "Pricing procedure determination or condition records are incomplete for the order context.",
        "checks": [
            "Analyze the pricing procedure and missing step on the sales document.",
            "Check condition records in VK13 or VK11.",
            "Validate sales area, customer, material, and date validity.",
        ],
        "resolution": [
            "Create or correct the missing condition record in VK11.",
            "Review pricing procedure determination and access sequence configuration.",
            "Reprice the order and confirm expected values appear.",
        ],
        "escalate_if": [
            "Custom pricing logic or exits are involved.",
            "The issue affects many customers or order types.",
        ],
    },
    {
        "id": "delivery_pgi_block",
        "title": "Post goods issue is blocked during delivery processing",
        "area": "SD",
        "symptoms": ["pgi failed", "post goods issue error", "delivery cannot post"],
        "keywords": ["pgi", "delivery", "vl02n", "goods", "issue"],
        "error_signals": ["post goods issue not possible", "picking not complete"],
        "tcodes": ["VL02N", "VL06O", "MMBE", "VFX3"],
        "root_cause": "Picking, stock, batch, or delivery status issues prevent PGI completion.",
        "checks": [
            "Review the exact delivery error and status in VL02N.",
            "Check picking status, stock, and batch determination.",
            "Confirm whether preceding documents or blocks are incomplete.",
        ],
        "resolution": [
            "Complete picking or correct stock and batch issues.",
            "Remove delivery blocks if business approved.",
            "Retry PGI and validate downstream billing readiness.",
        ],
        "escalate_if": [
            "WM/EWM integration is involved.",
            "A broader stock inconsistency is suspected.",
        ],
    },
    {
        "id": "payment_run_error",
        "title": "Automatic payment run proposal or execution failed",
        "area": "FI",
        "symptoms": ["payment run failed", "f110 error", "proposal error"],
        "keywords": ["payment", "f110", "proposal", "vendor", "bank"],
        "error_signals": ["proposal not created", "payment method missing", "bank data incomplete"],
        "tcodes": ["F110", "FBL1N", "FK02", "FBZP"],
        "root_cause": "Vendor, bank, payment method, or customizing data is incomplete for payment processing.",
        "checks": [
            "Review payment proposal logs in F110.",
            "Check vendor master bank and payment method data.",
            "Validate FBZP configuration and due items in FBL1N.",
        ],
        "resolution": [
            "Correct vendor bank, payment method, or payment block settings.",
            "Fix missing customizing if the run configuration is incomplete.",
            "Regenerate the proposal and confirm items are selected correctly.",
        ],
        "escalate_if": [
            "Payment file generation or bank interface is failing.",
            "Treasury or FI configuration changes are required.",
        ],
    },
    {
        "id": "document_number_range",
        "title": "Posting failed because a document number range is exhausted or missing",
        "area": "FI",
        "symptoms": ["number range error", "document number missing", "posting failed number range"],
        "keywords": ["number", "range", "fbn1", "snro", "document"],
        "error_signals": ["interval does not exist", "number range exhausted"],
        "tcodes": ["FBN1", "SNRO", "OBH2"],
        "root_cause": "The required number range interval is missing, closed, or exhausted for the fiscal year.",
        "checks": [
            "Check the exact object and fiscal year of the failed posting.",
            "Review interval maintenance in FBN1 or SNRO.",
            "Confirm whether transport or year-end setup missed the interval.",
        ],
        "resolution": [
            "Maintain the correct number range interval for the relevant year.",
            "Retry the posting once the interval is active.",
            "Validate that downstream posting objects use the expected range.",
        ],
        "escalate_if": [
            "Production number range design must be changed.",
            "Audit or finance approval is needed for interval adjustments.",
        ],
    },
    {
        "id": "sql_error_dump",
        "title": "DBIF_RSQL_SQL_ERROR or database SQL dump",
        "area": "Basis",
        "symptoms": ["sql error dump", "dbif_rsql_sql_error", "database dump"],
        "keywords": ["sql", "dbif_rsql_sql_error", "database", "dump", "st22"],
        "error_signals": ["dbif_rsql_sql_error", "sql code", "sql error"],
        "tcodes": ["ST22", "DBACOCKPIT", "ST05", "SM21"],
        "root_cause": "A database error, invalid SQL, missing object, or DB resource issue caused the ABAP statement to fail.",
        "checks": [
            "Review the full dump text and SQL error code in ST22.",
            "Check the database alert logs and DBACOCKPIT details.",
            "Trace the statement if the issue is reproducible.",
        ],
        "resolution": [
            "Correct database availability or object consistency problems.",
            "If the SQL itself is wrong, hand the failing report or program to ABAP support.",
            "Retest only after the underlying DB or code issue is fixed.",
        ],
        "escalate_if": [
            "The issue affects multiple transactions or core posting logic.",
            "DBA or developer intervention is required.",
        ],
    },
]
